version: "3"
services:
  app:
    user: "${UID}:${GID}"
    build:
      context: .
      dockerfile: ./node/Dockerfile
    restart: always
    tty: true
    volumes:
      - ./src:/app
    ports:
      - "3000:3000"
    command: sh -c "yarn dev"